cp intensity/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_1_123/training_set/intensity/img/
cp intensity/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_1_123/training_set/intensity/npy/
cp phase/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_1_123/training_set/phase/img/
cp phase/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_1_123/training_set/phase/npy/
cp zernikes/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_1_123/training_set/zernikes/
cp intensity/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_2_123/training_set/intensity/img/
cp intensity/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_2_123/training_set/intensity/npy/
cp phase/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_2_123/training_set/phase/img/
cp phase/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_2_123/training_set/phase/npy/
cp zernikes/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_2_123/training_set/zernikes/
cp intensity/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_3_123/training_set/intensity/img/
cp intensity/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_3_123/training_set/intensity/npy/
cp phase/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_3_123/training_set/phase/img/
cp phase/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_3_123/training_set/phase/npy/
cp zernikes/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_3_123/training_set/zernikes/
cp intensity/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_4_123/training_set/intensity/img/
cp intensity/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_4_123/training_set/intensity/npy/
cp phase/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_4_123/training_set/phase/img/
cp phase/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_4_123/training_set/phase/npy/
cp zernikes/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_4_123/training_set/zernikes/
cp intensity/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_5_123/training_set/intensity/img/
cp intensity/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_5_123/training_set/intensity/npy/
cp phase/img/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_5_123/training_set/phase/img/
cp phase/npy/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_5_123/training_set/phase/npy/
cp zernikes/* ../../SDDAL_InShaPe_randinit_syncUNet_varseed/Design_rec_5_123/training_set/zernikes/